"""
Image management utilities for the Multi-Agent Orchestrator system.

This module handles saving, managing, and organizing images generated by
the code interpreter agent.
"""

import os
import base64
import logging
from datetime import datetime
from typing import List, Optional, Dict, Any
from pathlib import Path
import uuid

logger = logging.getLogger('multi_agent_orchestrator.image_manager')

class ImageManager:
    """Manages image files generated by the code interpreter agent."""

    def __init__(self, base_temp_dir: str = None, project_client = None):
        """Initialize the image manager with a temporary directory."""
        if base_temp_dir is None:
            # Default to temp/images directory in project root
            project_root = Path(__file__).parent.parent
            base_temp_dir = project_root / "temp" / "images"

        self.temp_dir = Path(base_temp_dir)
        self.temp_dir.mkdir(parents=True, exist_ok=True)
        self.project_client = project_client

        logger.info(f"ImageManager initialized with temp directory: {self.temp_dir}")

    def download_image_from_azure(self, file_id: str) -> Optional[str]:
        """
        Download an image file from Azure AI using the correct SDK method.

        Args:
            file_id: Azure AI file ID

        Returns:
            Path to the downloaded image file, or None if download failed
        """
        if not self.project_client:
            logger.error("No Azure project client available for file download")
            return None

        try:
            # Generate a filename for the downloaded image
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"azure_image_{file_id[:8]}_{timestamp}.png"
            file_path = self.temp_dir / filename

            # Use the correct Azure AI SDK method to save the file
            self.project_client.agents.files.save(
                file_id=file_id,
                file_name=str(file_path)
            )

            logger.info(f"Successfully downloaded image from Azure AI to: {file_path}")
            return str(file_path)

        except Exception as e:
            logger.error(f"Error downloading image from Azure AI (file_id: {file_id}): {str(e)}")

            # Create a placeholder file with error information
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            placeholder_filename = f"placeholder_error_{file_id[:8]}_{timestamp}.txt"
            placeholder_path = self.temp_dir / placeholder_filename

            with open(placeholder_path, 'w') as f:
                f.write(f"Failed to download image from Azure AI\n")
                f.write(f"File ID: {file_id}\n")
                f.write(f"Error: {str(e)}\n")
                f.write(f"Timestamp: {datetime.now().isoformat()}\n")

            logger.info(f"Created error placeholder file: {placeholder_path}")
            return None

    def save_image_from_base64(self, base64_data: str, filename: Optional[str] = None,
                              file_extension: str = "png") -> str:
        """
        Save a base64-encoded image to the temporary directory.

        Args:
            base64_data: Base64-encoded image data
            filename: Optional custom filename (without extension)
            file_extension: File extension (default: png)

        Returns:
            Path to the saved image file
        """
        try:
            # Generate filename if not provided
            if filename is None:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                unique_id = str(uuid.uuid4())[:8]
                filename = f"image_{timestamp}_{unique_id}"

            # Ensure proper file extension
            if not filename.endswith(f".{file_extension}"):
                filename = f"{filename}.{file_extension}"

            file_path = self.temp_dir / filename

            # Decode and save the image
            image_data = base64.b64decode(base64_data)

            with open(file_path, 'wb') as f:
                f.write(image_data)

            logger.info(f"Image saved: {file_path}")
            return str(file_path)

        except Exception as e:
            logger.error(f"Error saving image: {str(e)}")
            raise

    def save_image_from_bytes(self, image_bytes: bytes, filename: Optional[str] = None,
                             file_extension: str = "png") -> str:
        """
        Save image bytes to the temporary directory.

        Args:
            image_bytes: Raw image data as bytes
            filename: Optional custom filename (without extension)
            file_extension: File extension (default: png)

        Returns:
            Path to the saved image file
        """
        try:
            # Generate filename if not provided
            if filename is None:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                unique_id = str(uuid.uuid4())[:8]
                filename = f"image_{timestamp}_{unique_id}"

            # Ensure proper file extension
            if not filename.endswith(f".{file_extension}"):
                filename = f"{filename}.{file_extension}"

            file_path = self.temp_dir / filename

            # Save the image
            with open(file_path, 'wb') as f:
                f.write(image_bytes)

            logger.info(f"Image saved: {file_path}")
            return str(file_path)

        except Exception as e:
            logger.error(f"Error saving image: {str(e)}")
            raise

    def extract_and_save_images_from_message(self, message_content: Any) -> List[str]:
        """
        Extract and save images from Azure AI message content.

        Args:
            message_content: Azure AI message content that may contain images

        Returns:
            List of paths to saved image files
        """
        saved_images = []

        try:
            if hasattr(message_content, 'content') and message_content.content:
                content_items = message_content.content if isinstance(message_content.content, list) else [message_content.content]

                for item in content_items:
                    # Check for image content
                    if hasattr(item, 'type') and item.type == 'image_file':
                        # Handle image file content
                        if hasattr(item, 'image_file') and hasattr(item.image_file, 'file_id'):
                            # Download the file from Azure AI
                            file_id = item.image_file.file_id
                            logger.info(f"Found image file with ID: {file_id}")

                            try:
                                saved_path = self.download_image_from_azure(file_id)
                                if saved_path:
                                    saved_images.append(saved_path)
                                    logger.info(f"Downloaded and saved image from Azure AI: {saved_path}")
                            except Exception as e:
                                logger.error(f"Failed to download image {file_id}: {str(e)}")

                    elif hasattr(item, 'image_url'):
                        # Handle image URL content
                        if hasattr(item.image_url, 'url'):
                            url = item.image_url.url
                            if url.startswith('data:image'):
                                # Extract base64 data from data URL
                                header, base64_data = url.split(',', 1)

                                # Determine file extension from header
                                if 'png' in header:
                                    ext = 'png'
                                elif 'jpeg' in header or 'jpg' in header:
                                    ext = 'jpg'
                                elif 'gif' in header:
                                    ext = 'gif'
                                else:
                                    ext = 'png'  # default

                                saved_path = self.save_image_from_base64(base64_data, file_extension=ext)
                                saved_images.append(saved_path)
                                logger.info(f"Extracted and saved image from data URL: {saved_path}")

        except Exception as e:
            logger.error(f"Error extracting images from message: {str(e)}")

        return saved_images